/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PubPriPro;

public class App {
    public static void main(String args[]) {
   Caneta caneta1 = new Caneta();
   caneta1.modelo = "Mont Blanc";
   caneta1.cor = "azul";
   caneta1.ponta = 0.7f;
   caneta1.carga = 77;
 //  caneta1.tampada = true;
 caneta1.destampar ();
   caneta1.rabiscar();
         caneta1.status();
   
    }
       }
